# Generated by Django 5.0.1 on 2025-11-13 00:42

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Inventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=50, unique=True)),
                ("nombre", models.CharField(max_length=200)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("medicamento", "Medicamento"),
                            ("alimento", "Alimento"),
                            ("accesorio", "Accesorio"),
                            ("equipamiento", "Equipamiento"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
                (
                    "cantidad",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("unidad_medida", models.CharField(max_length=50)),
                (
                    "precio_unitario",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "stock_minimo",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("fecha_vencimiento", models.DateField(blank=True, null=True)),
                ("proveedor", models.CharField(blank=True, max_length=200)),
                ("activo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Producto de Inventario",
                "verbose_name_plural": "Inventario",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Mascota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("especie", models.CharField(max_length=50)),
                ("raza", models.CharField(max_length=100)),
                ("fecha_nacimiento", models.DateField()),
                (
                    "sexo",
                    models.CharField(
                        choices=[("Macho", "Macho"), ("Hembra", "Hembra")],
                        max_length=10,
                    ),
                ),
                ("color", models.CharField(max_length=50)),
                (
                    "peso_kg",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "foto_url",
                    models.ImageField(
                        blank=True, null=True, upload_to="fotos_mascotas/"
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Mascota",
                "verbose_name_plural": "Mascotas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Rol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        choices=[
                            ("administrador", "Administrador"),
                            ("veterinario", "Veterinario"),
                            ("tutor", "Tutor"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Rol",
                "verbose_name_plural": "Roles",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Tutor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ci",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Cédula de Identidad"
                    ),
                ),
                ("direccion", models.TextField()),
                ("fecha_nacimiento", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tutor",
                "verbose_name_plural": "Tutores",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HistorialMedico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("consulta", "Consulta"),
                            ("vacunacion", "Vacunación"),
                            ("cirugia", "Cirugía"),
                            ("emergencia", "Emergencia"),
                        ],
                        max_length=20,
                    ),
                ),
                ("diagnostico", models.TextField()),
                ("tratamiento", models.TextField()),
                ("medicamentos", models.TextField(blank=True)),
                (
                    "peso_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "temperatura_c",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("proxima_visita", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mascota",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historiales",
                        to="api.mascota",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial Médico",
                "verbose_name_plural": "Historiales Médicos",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="RecetaMedicamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dosis",
                    models.CharField(
                        help_text="Ej: 1 tableta, 5ml, etc.", max_length=100
                    ),
                ),
                (
                    "frecuencia",
                    models.CharField(
                        help_text="Ej: Cada 8 horas, 2 veces al día, etc.",
                        max_length=100,
                    ),
                ),
                (
                    "duracion",
                    models.CharField(
                        help_text="Ej: 7 días, 2 semanas, etc.", max_length=100
                    ),
                ),
                (
                    "instrucciones",
                    models.TextField(blank=True, help_text="Instrucciones adicionales"),
                ),
                (
                    "cantidad_total",
                    models.IntegerField(
                        help_text="Cantidad total de unidades recetadas",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "historial_medico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recetas",
                        to="api.historialmedico",
                    ),
                ),
                (
                    "medicamento",
                    models.ForeignKey(
                        limit_choices_to={"categoria": "medicamento"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recetas",
                        to="api.inventario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Receta de Medicamento",
                "verbose_name_plural": "Recetas de Medicamentos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="mascota",
            name="tutor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mascotas",
                to="api.tutor",
            ),
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password_hash", models.CharField(max_length=255)),
                ("nombre_completo", models.CharField(max_length=200)),
                ("telefono", models.CharField(blank=True, max_length=20)),
                ("activo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarios",
                        to="api.rol",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="tutor",
            name="usuario",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tutor",
                to="api.usuario",
            ),
        ),
        migrations.CreateModel(
            name="MovimientoInventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_movimiento",
                    models.CharField(
                        choices=[
                            ("entrada", "Entrada"),
                            ("salida", "Salida"),
                            ("ajuste", "Ajuste"),
                        ],
                        max_length=20,
                    ),
                ),
                ("cantidad", models.IntegerField()),
                ("motivo", models.TextField()),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "inventario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos",
                        to="api.inventario",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos_inventario",
                        to="api.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de Inventario",
                "verbose_name_plural": "Movimientos de Inventario",
                "ordering": ["-fecha"],
            },
        ),
        migrations.AddField(
            model_name="historialmedico",
            name="veterinario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="historiales_realizados",
                to="api.usuario",
            ),
        ),
        migrations.CreateModel(
            name="Cita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_hora", models.DateTimeField()),
                ("motivo", models.TextField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("confirmada", "Confirmada"),
                            ("completada", "Completada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mascota",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="citas",
                        to="api.mascota",
                    ),
                ),
                (
                    "veterinario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="citas_veterinario",
                        to="api.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cita",
                "verbose_name_plural": "Citas",
                "ordering": ["-fecha_hora"],
            },
        ),
    ]
