# Generated by Django 5.0.1 on 2025-11-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="especialidad",
            field=models.CharField(
                blank=True,
                choices=[
                    ("general", "Medicina General"),
                    ("cirugia", "Cirugía"),
                    ("dermatologia", "Dermatología"),
                    ("cardiologia", "Cardiología"),
                    ("oftalmologia", "Oftalmología"),
                    ("traumatologia", "Traumatología"),
                    ("odontologia", "Odontología"),
                    ("neurologia", "Neurología"),
                    ("oncologia", "Oncología"),
                ],
                help_text="Especialidad del veterinario (solo aplica para veterinarios)",
                max_length=50,
                null=True,
            ),
        ),
    ]
